export const AUTH_REPOSITORY = Symbol("AUTH_REPOSITORY");
export const PASSWORD_HASHER = Symbol("PASSWORD_HASHER");
export const SESSION_CREDENTIAL_ISSUER = Symbol("SESSION_CREDENTIAL_ISSUER");
export const AUTH_CLOCK = Symbol("AUTH_CLOCK");
export const AUTH_RUNTIME_CONFIG = Symbol("AUTH_RUNTIME_CONFIG");
export const ONE_TIME_SECRET_ISSUER = Symbol("ONE_TIME_SECRET_ISSUER");
export const AUTH_KEY_HASHER = Symbol("AUTH_KEY_HASHER");
export const AUTH_ABUSE_CONTROL = Symbol("AUTH_ABUSE_CONTROL");
export const AUTH_SECURITY_AUDIT_SERVICE = Symbol(
  "AUTH_SECURITY_AUDIT_SERVICE",
);
export const VERIFICATION_DELIVERY = Symbol("VERIFICATION_DELIVERY");
export const PASSWORD_RECOVERY_DELIVERY = Symbol("PASSWORD_RECOVERY_DELIVERY");
export const AUTH_FAKE_DELIVERY = Symbol("AUTH_FAKE_DELIVERY");
