export const ADMIN_REPOSITORY = Symbol("ADMIN_REPOSITORY");
export const ADMIN_CREDENTIAL_READER = Symbol("ADMIN_CREDENTIAL_READER");
export const ADMIN_PASSWORD_HASHER = Symbol("ADMIN_PASSWORD_HASHER");
export const ADMIN_CLOCK = Symbol("ADMIN_CLOCK");
